### ISSUE TITLE
Using periods in tags

### ISSUE THREAD

**Issue by zoe-edwards** [Medalink/laravel-blade#185] opened 2020-05-08 16:53 UTC
In Laravel 7 we can use periods in component tags.

<img width="484" alt="Screenshot 2020-05-08 at 17 52 09" src="https://user-images.githubusercontent.com/354995/81428804-b64cfa80-9154-11ea-9d8c-d6f70d2d46a1.png">

However they show up as an aa problem (reasonably!) when using the highlighter.

**Comment by stuartcusackie** [comment] 2020-07-16 23:37
Same problem. It's a nice new feature but quite distracting to see those pink boxes!

**Comment by MikeHopley** [comment] 2020-07-20 09:57
Also colons with Livewire:
![liverwire-blade-syntax](https://user-images.githubusercontent.com/856145/87925135-c3049d80-ca77-11ea-8ff8-60a98b6e34a4.png)

**Comment by indigoram89** [comment] 2020-09-30 11:09
+1

Any ideas?

**Comment by jianjye** [comment] 2020-10-02 08:59
Having this issue as well. Has anyone found any fixes yet?

**Comment by eklundkristoffer** [comment] 2020-10-08 19:16
May not be a good solution for everyone, but personally I don't need this error highlighting at all so I just removed it in the color scheme file. For example, in my `Nord.sublime-color-scheme` I removed the `invalid.illegal` scope row.

```json
{
  "name": "[Invalid] Illegal",
  "scope": "invalid.illegal",
  "foreground": "var(nord4)",
  "background": "var(nord_error)"
},
````

Please not that this will turn off  **ALL** `invalid.illegal` highlighting.

**Comment by rcyberdog** [comment] 2020-10-31 19:20
![imagen](https://user-images.githubusercontent.com/73757961/97788061-c50ceb00-1b94-11eb-98eb-2a320ea19d24.png)

It's worst with both (colon and dot), when you insert a Livewire Component inside a subfolder.

**Comment by jianjye** [comment] 2020-11-01 06:31
The issue is likely due to colons and dots not being valid HTML syntax so they are highlighted as errors by the default Sublime HTML syntax highlighter. 

To handle this, we need a new section to match our use cases inside the `blade.sublime-syntax` file. 

I couldn't get it working myself,  perhaps someone else with better regex knowledge can build on top of my findings and submit a fix.

**Comment by stuartcusackie** [comment] 2021-02-20 15:35
I had a stab at it but it seems like you would have to duplicate a lot of code from sublime's default HTML.sublime-syntax file and modify it to allow dots.

Need someone with more experience in this sort of thing.

**Comment by mylesduncanking** [comment] 2021-03-10 12:59
This may be a solution but it may also have room for improvement: [Pull request #190](https://github.com/Medalink/laravel-blade/pull/190)

**Comment by deathaxe** [comment] 2022-12-20 14:53
This issue is fixed by ST 4107+. It provides an updated HTML syntax with support for delimiters.

**Closed** 2022-12-24 18:03 UTC
