### ISSUE TITLE
Stop Working in Sublime Text 3114

### ISSUE THREAD

**Issue by David-Kurniawan** [Medalink/laravel-blade#113] opened 2016-05-17 15:11 UTC

**Comment by orosznyet** [comment] 2016-05-18 12:31
I can confirm this.

**Comment by cillosis** [comment] 2016-05-19 19:40
I can also confirm this.

**Comment by sakib11** [comment] 2016-05-27 06:25
Same here. Doesn't work on sublime text 3114

**Comment by sakib11** [comment] 2016-05-27 06:25
please solve this

**Comment by Medalink** [comment] 2016-05-30 12:40
I just tested v1.5.8.2 on ST 3114 and it's working correctly for me. What problems are you guys experiencing? Can you past a list of plugins you are using as well as any errors present in the ST console?

**Comment by tam5** [comment] 2016-06-01 15:10
For my **ST 3114** this was not working as well. Additionally, there was no menu option for the plugin in Package Settings, though I was able to confirm that it is installed through the command palette.

The ST console had the following:
```
ignored packages updated to: ["Laravel Blade Highlighter", "SideBarEnhancements", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error parsing messages.json for Laravel Blade Highlighter
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["SideBarEnhancements", "Vintage"]
```

As I was writing this I was going to write a list of my installed packages. While doing so I decided to remove one, namely 'Markdown Preview' (because I had another similar package). For some reason after I removed this package, Laravel Blade was working. I also reinstalled the 'Markdown Preview' package to see what would happen, and Laravel Blade still works.

So....

As a quick fix it seems you can uninstall and reinstall 'Markdown Preview' (or maybe any other package? I'm not sure about this).

Eventually it would be great to find whatever causes this bug and fix it.

I was also not able to reproduce the error. I removed the Laravel Blade package and reinstalled, but it worked the second time too so I was not able to reproduce the bug.

I hope this helps..

**Comment by Medalink** [comment] 2016-06-01 21:38
This should be fixed now.

**Comment by jbrooksuk** [comment] 2016-06-03 15:28
Closing this.

**Closed by jbrooksuk** 2016-06-03 15:28 UTC
